import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM="xterm-256color"

[window]
padding.x = 10 
padding.y = 10

opacity = 0.8
blur = false

decorations = "ButtonLess"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 13
